version: 0.2

phases:
  install:
    commands:
      - set -e
      - echo Installing dependencies...
      - python3 -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
artifacts:
  files:
    - '**/*'